import os, sys, datetime, unicodedata, re, pytz
from datetime import datetime, timezone

# usage: python newblog.py `date -Iseconds` "title"

if len(sys.argv) < 3:
    raise RuntimeError("Missing arguments (requiring 2)")

tmpl = """
# -- DO NOT CHANGE ANYTHING BELOW --
# Generated by /scripts/newblog.py
export const creation_time = "{time}";
export const title = "{title}";
"""

creation_time = datetime.fromisoformat(sys.argv[1])
creation_time = creation_time.astimezone(timezone.utc)

file_name = unicodedata.normalize('NFKD', sys.argv[2])
file_name = file_name.encode('ascii', 'ignore').decode('ascii')
file_name = re.sub(r'[^\w\s-]', '', file_name.lower())
file_name = re.sub(r'[-\s]+', '-', file_name).strip('-_')
file_name += "-" + creation_time.strftime("%Y-%m-%d") + ".mdx"

path = '{}/src/app/blogs/[blogId]/{}'.format(os.getcwd(), file_name)
if os.path.exists(path):
    raise RuntimeError("File/Directory exists: {}".format(path))
with open(path, "w", encoding='utf-8') as f:
    f.write(tmpl.format(time=creation_time.strftime("%Y-%m-%dT%H:%M:%S"),
                        title=sys.argv[2]))